### ISSUE TITLE
getERC20 not working

### ISSUE THREAD

**Issue by 7flash** [kyscott18/reverse-mirage#66]
Given following code

```
import { publicActionReverseMirage, amountToNumber } from 'reverse-mirage'

window.publicEthClient = createPublicClient({
  chain: mainnet,
  transport: http()
}).extend(publicActionReverseMirage)

await publicEthClient.getERC20({
  address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', // usdc
  id: 1,
})
```

throws an error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'address')
    at getERC20Name (index.js:1033:18)
    at getERC20 (index.js:1046:3)
    at Object.getERC20 (index.js:1672:23)
    at <anonymous>:1:23
```

<img width="574" alt="Screenshot 2024-03-15 at 17 25 55" src="https://github.com/kyscott18/reverse-mirage/assets/4569866/2853b977-181c-45a7-b36a-76aae3a6694b">

**Comment by kyscott18** [comment]
You're passing in the wrong arguments to the function. Should be:
```ts
await publicEthClient.getERC20({
  erc20: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', // usdc
  id: 1,
})
```

What you have might be more intuitive, will think about changing it
